### ISSUE TITLE
Android Basics: Forage app

### ISSUE THREAD

**Issue by abdellatifdarmellah** [google-developer-training/android-basics-kotlin-forage-app#13]
When I start Testing my app I face this problem: 
"Run Android instrumented tests using Gradle" option was ignored because this module type is not supported yet.

I tried to change the versions of the implementations and still not fixed and  when I disabled "Run android instrumented tests using gradle"  the error doesn't show again because the tests are not passing at all

Any solution !! ( I tried the app by my self and it's working)
![Screenshot_20220929_144156](https://user-images.githubusercontent.com/76949906/193047771-6d3c5a11-a158-4718-8599-28f6e0accbeb.png)

**Comment by casti093** [comment]
I also came across this error, couldn't really find a solution. I switched emulator, I was first using [Pixel 5 API 31] and was seeing the same error as you, I then switched to [Pixel C API 30] and the tests ran. But this isn't really a solution since you would want your app to work with different phones and models. Have you found anything??
